# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memento < Formula
  desc "A markdown-based, in-repo memory substrate for AI coding agents."
  homepage "https://github.com/tpisel/memento"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tpisel/memento/releases/download/v0.4.0/memento_darwin_amd64.tar.gz"
      sha256 "514cd9258d2683a1f13e834a5d36a5d7d00bc6847db3c6c9bac348296c47ef33"

      define_method(:install) do
        bin.install "memento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tpisel/memento/releases/download/v0.4.0/memento_darwin_arm64.tar.gz"
      sha256 "c2d0bf0a94ec8be4c0a4474e6acbb4615e2deb43cb4de5bc855b73c3769ca02e"

      define_method(:install) do
        bin.install "memento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tpisel/memento/releases/download/v0.4.0/memento_linux_amd64.tar.gz"
      sha256 "ce7230a2d39675f2ccc10091dafb304715f015a8edf0db99a282ca06386ff5ea"
      define_method(:install) do
        bin.install "memento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tpisel/memento/releases/download/v0.4.0/memento_linux_arm64.tar.gz"
      sha256 "6caf93b3e156827a3ac921433172311332b19c1b219a26b4d5f54b9e9ac7a65f"
      define_method(:install) do
        bin.install "memento"
      end
    end
  end
end
