# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memento < Formula
  desc "A markdown-based, in-repo memory substrate for AI coding agents."
  homepage "https://github.com/tpisel/memento"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tpisel/memento/releases/download/v0.3.0/memento_darwin_amd64.tar.gz"
      sha256 "b19936e5d7f089b249dffe22509b189c8be10557ef821267ce521135ef0bf4b3"

      define_method(:install) do
        bin.install "memento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tpisel/memento/releases/download/v0.3.0/memento_darwin_arm64.tar.gz"
      sha256 "3ebbae5d2a5dee2653979aec3849b2544ed74c77afe62d6ae03cb8f5a7caeb3e"

      define_method(:install) do
        bin.install "memento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tpisel/memento/releases/download/v0.3.0/memento_linux_amd64.tar.gz"
      sha256 "c53a674398097fc8c3d823288c56151aefb386b7b078ed12cb667555d5b30cb7"
      define_method(:install) do
        bin.install "memento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tpisel/memento/releases/download/v0.3.0/memento_linux_arm64.tar.gz"
      sha256 "7519ff469c50931806e29fdb3dc044fa04b483c1921ea92d79b9599cad155843"
      define_method(:install) do
        bin.install "memento"
      end
    end
  end
end
